package leetcode_dcc.mar_26;
/*
3474. Lexicographically Smallest Generated String (Hard)
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
Example 1:
Input: str1 = "TFTF", str2 = "ab"
Output: "ababa"
Explanation:
The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.
Streak->237
* */
import java.util.Arrays;
public class LexicographicallySmallestGeneratedString {
    public static void main(String[] args) {

    }
    public static String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        char[] word = new char[n + m - 1];
        boolean[] locked = new boolean[n + m - 1];
        Arrays.fill(word, '#');
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    int idx = i + j;
                    if (word[idx] == '#' || word[idx] == str2.charAt(j)) {
                        word[idx] = str2.charAt(j);
                        locked[idx] = true;
                    } else {
                        return "";
                    }
                }
            }
        }
        for (int i = 0; i < word.length; i++) {
            if (word[i] == '#') {
                word[i] = 'a';
            }
        }

        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'F') {

                if (matches(word, i, str2)) {

                    boolean fixed = false;

                    for (int j = m - 1; j >= 0; j--) {
                        int idx = i + j;

                        if (locked[idx])
                            continue;

                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c != str2.charAt(j)) {
                                word[idx] = c;
                                fixed = true;
                                break;
                            }
                        }

                        if (fixed)
                            break;
                    }

                    if (!fixed)
                        return "";
                }
            }
        }

        return new String(word);
    }

    private static boolean matches(char[] word, int start, String str2) {
        for (int j = 0; j < str2.length(); j++) {
            if (word[start + j] != str2.charAt(j)) {
                return false;
            }
        }
        return true;
    }
}
